[package]
name = "mdbook-qa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.6"
mdbook = "0.4.35"
regex = "1.10.0"
serde_json = "1.0.107"
lazy_static = "1.4.0"
log = "0.4.20"